### ISSUE TITLE
"MEMORY Usage" just keeps going up, past 100%.

### ISSUE THREAD

**Issue by brienhopkins** [0ather/AFX-CpuRamMonitor#1]
This is an awesome tool. However, I've noticed the Memory reading seems broken. Activity monitor shows 43/64GB memory used, while the panel in Ae says 271%. In fact, it doesn't go down unless I purge memory the old fashion way. I'm using After Effects CC2015 version 13.6.1.6

Thanks,
Brien

**Comment by 0ather** [comment]
Hi Brien!

Thanks for trying my extension! Just a few questions:
What is your OS?
When you empty the cache with the extension, the memory monitor don't go down but when you empty the cache with the build in option (edit, purge, all memory) it work, I am right?

I'm gonna work on it!
Thanks :)

**Comment by brienhopkins** [comment]
I'm on El Capitan v10.11.1

Yes, that's correct. I think the extension DOES purge the memory, but the reading on blue bar doesn't reflect that.

Brien

**Comment by 0ather** [comment]
Yep alright. I didn't check the compatibility on OSX El Capitan so it might be a clue :)

I'll check asap!

**Comment by 0ather** [comment]
Hey Brien, 
Could you check the new version? It should be working now!

Cheers!

**Comment by brienhopkins** [comment]
Been trying it for about an hour. Memory reads 144% at the moment.

**Comment by 0ather** [comment]
Hum okay that's weird because it call the built-in action! The empty cache button really work? Does it empty your cache but doesn't empty your memory?

**Comment by brienhopkins** [comment]
It empties both my cache and my memory. However, the memory indicator bar is incorrect. I can't be using over 100% of my memory, right?

**Comment by 0ather** [comment]
OK I'll have a second look tomorrow ;)

**Comment by 0ather** [comment]
Hi Brien!

Could you try this test version? It will also show you the calculated amount of ram so you can see if all the data are right!

Cheers!

[CPU-Ram-Monitor.zip](https://github.com/0ather/AFX-CpuRamMonitor/files/101862/CPU-Ram-Monitor.zip)

**Comment by brienhopkins** [comment]
Hi Florian,

The version you linked to seems to be working. When I start up Ae, it reads
about 18% memory, which seems more accurate. However, it says there's an
update to download. When I installed that update, and restarted Ae, the
script read my system memory usage at 78%. I did not increase my memory
usage _that_ much while installing the update. So I rolled back to the
version you sent in the link above, and now it's back at 18% again. Here's
a screenshot:

https://www.dropbox.com/s/n708w4iow4xubdy/Screenshot%202016-01-26%2009.52.22.png?dl=0

If I may, the new "total memory" and "used memory" text is a waste of
valuable screen real-estate. The loading bar you've designed portrays that
information quite well already.

Thanks,
Brien

**Comment by 0ather** [comment]
Hi Brien,

Yep as I said, the version I linked is just a test version so it was compiled just for you (lucky you!). Now that the issue is solved, I'm gonna "officially" release the fixed version of the extension.

Thanks for your time and support!

**Comment by brienhopkins** [comment]
Oh that makes more sense. I suspected as much. That's great. Thanks for the
quick responses and turn arounds on all this. One other thing, you may have
already considered; a scroll bar. When I expanded to "show all cores" I
could no longer see anything else, and had no means to scroll down to it.

Thanks,
Brien

**Comment by 0ather** [comment]
I actually noticed that when I was looking for the ram monitor issue. The scroll bar is hidden but you should be able to scroll with your mouse / trackpad!

**Comment by brienhopkins** [comment]
Ah-ha. Well, you've just thought of everything, haven't you.

**Comment by 0ather** [comment]
Ahah I tried!
If you think it would be more relevant to see the scrollbar, I can unhide it!

**Comment by brienhopkins** [comment]
No, I think it's good and minimal how you've designed it. So should I
install the linked file on Github now?

**Comment by 0ather** [comment]
Not yet, if you follow this github project (with the "watch" button at the top of your browser) you'll get a notification when new versions are online! If not just wait a bit, I'm trying to compile the extension so people can download it from the adobe exchange platform as well :)
