### ISSUE TITLE
Dragging another panel into this panel, as "stacked UI panels" causes Ae to crash.

### ISSUE THREAD

**Issue by brienhopkins** [0ather/AFX-CpuRamMonitor#2]
Manually work around is to drag this panel into the stack last, thereby avoiding dragging a panel into it. That said, dragging a panel into it does cause Ae to crash.

Mac OS El Capitan 10.11.1
After Effects CC 2015 13.6.1.6

**Comment by brienhopkins** [comment]
Hm. Seems solved the most recent update.

**Comment by 0ather** [comment]
Hi again!

Wow that sounds weird! I never did that before because I just dragged and drop the extension panel into another!
Did it happened after a long use of after effects or did you dragged the panel right after opening After Effects?
I'm gonna check that!

Cheers
Florian

**Comment by brienhopkins** [comment]
I tested it out a few times. It would happen first thing.

**Comment by 0ather** [comment]
I tried on Yosemite and El Capitan 10.11.2, no sign of your issue... Did it happened with a specific panel? On a particular place?

**Comment by brienhopkins** [comment]
Hm. Upon further testing, it seems it only happens when dragging in the
"Explode Shape Layers" panel.

**Comment by 0ather** [comment]
Okay so I guess there is no real possible fix for that!
Sorry about that.

Cheers,
Florian
