### ISSUE TITLE
Cache monitor never stops "Loading..." for secondary SSD

### ISSUE THREAD

**Issue by brienhopkins** [0ather/AFX-CpuRamMonitor#3]
Hello. I've just installed a secondary SSD on my system, and directed Ae to write cache files to it. That all seems to be working. However, the cache monitor on this panel doesn't seem to see it. It just keeps "loading..."

Thanks,
Brien

**Comment by brienhopkins** [comment]
Actually,

Now the whole panel won't load. just says "loading..." forever.

Brien

**Comment by 0ather** [comment]
Sorry about that, the update should fix your problem ;)

**Comment by brienhopkins** [comment]
Indeed, it did. Thanks!
